apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timecalc
  labels:
    app: timecalc
spec:
  ingressClassName: nginx
  rules:
    - host: timecalc.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: timecalc
                port:
                  number: 80
