apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecalc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: timecalc
  template:
    metadata:
      labels:
        app: timecalc
    spec:
      containers:
        - name: timecalc
          image: appleweek/timecalc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: timecalc-pvc
